### ISSUE TITLE
panic: No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by itamaro** [jbeda/tgik-controller#1]
just finished catching up on the last TGIK (timezone...) - really enjoyed that one - thanks! :-)

trying to follow along with a controller from the "initial point" (commit 13db5aa), running it as is on my MacBook against my k8s cluster on GKE, I get an error about GCP Auth:

```
>KUBECONFIG=~/.kube/config go run *.go
2017/08/12 11:51:17 tgik-controller version UNKNOWN
panic: No Auth Provider found for name "gcp"

goroutine 1 [running]:
github.com/jbeda/tgik-controller/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1.NewForConfigOrDie(0xc4200ff880, 0xc4200a91e0)
	/Users/itamar/go/src/github.com/jbeda/tgik-controller/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1/admissionregistration_client.go:63 +0x62
github.com/jbeda/tgik-controller/vendor/k8s.io/client-go/kubernetes.NewForConfigOrDie(0xc4200ff880, 0x0)
	/Users/itamar/go/src/github.com/jbeda/tgik-controller/vendor/k8s.io/client-go/kubernetes/clientset.go:519 +0x49
main.main()
	/Users/itamar/go/src/github.com/jbeda/tgik-controller/tgik-controller.go:39 +0x233
exit status 2
```

Am I missing something?

**Comment by itamaro** [comment]
ok, figured it out.

added the following line the the imports in `controller.go` (line 12):

    _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"

this triggered an error with `log_dir` flag redefinition, so I removed `vendor/github.com/golang/glog` (since I already have `glog` under `$GOPATH`).

then the "No Auth provider found" error came back, so I removed also `vendor/k8s.io` (since I have up-to-date client-go & apimachinery under `$GOPATH`).

now it's working :-)

**Comment by jbeda** [comment]
Sorry I missed this bug report! Too many github emails flying around.

**Comment by itamaro** [comment]
> Sorry I missed this bug report! Too many github emails flying around.

understandable :-)

btw, what is the recommended way to deal with issues with duplicate dependencies between my `$GOPATH` and the vendor dir?

**Comment by jbeda** [comment]
I believe that the vendor dir will win for any dependency.  Generally, however, it is bad form for libraries to also vendor dependecies. This stuff is super complicated at the limit and none of the tools are there yet.  Lots of people are coalescing around dep as the solution but client-go isn't there yet.
